export const siteConfig = {
  title: 'Arockia Bilgates | Full-Stack Software Engineer | MERN | AI Applications | React | Node.js',
  description:
    'Arockia Bilgates is a Full-Stack Software Engineer based in Thanjavur, India, with 3+ years of experience building scalable MERN applications with Gemini AI integration. Specialises in React, Next.js, Node.js, Express, MongoDB, real-time systems with Socket.io, and production AI features.',
  keywords: [
    'Arockia Bilgates',
    'Full Stack Software Engineer',
    'MERN Stack Developer',
    'AI Integration Developer',
    'Gemini AI Developer',
    'React Developer',
    'Node.js Developer',
    'Next.js Developer',
    'MongoDB Developer',
    'Express.js Developer',
    'Web Developer Thanjavur',
    'Web Developer India',
    'Socket.io Developer',
    'Real-Time App Developer',
    'Java Spring Boot Developer',
    'Python Developer',
    'Docker',
    'AWS Developer',
    'REST API Developer',
    'Full Stack Web Developer India',
    'React.js Developer India',
    'Backend Developer',
    'AI Powered Web Apps',
    'arockiabilgates2@gmail.com',
  ],
  url: 'https://arockiabilgates.netlify.app',
  googleSiteVerificationId: '',
  locales: ['en'],
  defaultLocale: 'en',
};
